# Generated by Django 5.1 on 2024-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
            ],
        ),
    ]
