# Generated by Django 5.1 on 2024-10-15 01:13

import django.core.validators
import django.db.models.deletion
import pet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50, unique=True)),
                ('pet_breed', models.CharField(max_length=50)),
                ('pet_species', models.CharField(max_length=50)),
                ('pet_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age should be at least 1.')])),
                ('pet_image', models.ImageField(upload_to='user_pets/', validators=[pet.models.validate_image])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
