# Generated by Django 5.1 on 2024-11-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_fn', '0006_remove_adoptionapplication_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('cream', 'Cream'), ('yellow', 'Yellow'), ('golden', 'Golden'), ('orange', 'Orange'), ('brown', 'Brown'), ('red', 'Red')], default='grey', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='health',
            field=models.TextField(default='Healthy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images/', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='cat',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images/', verbose_name='Secondary Image'),
        ),
        migrations.AddField(
            model_name='cat',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images/', verbose_name='Third Image'),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='vaccinated',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cat_videos/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('cream', 'Cream'), ('golden', 'Golden'), ('orange', 'Orange'), ('brown', 'Brown'), ('red', 'Red')], default='white', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='health',
            field=models.TextField(default='healthy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='dog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/', verbose_name='Secondary Image'),
        ),
        migrations.AddField(
            model_name='dog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/', verbose_name='Third Image'),
        ),
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinated',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dog_videos/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(choices=[('american shorthair', 'American Shorthair'), ('bengal', 'Bengal'), ('birman', 'Birman'), ('british shorthair', 'British Shorthair'), ('egyptian mau', 'Egyptian Mau'), ('himalayan', 'Himalayan'), ('maine coon', 'Maine Coon'), ('manx', 'Manx'), ('norwegian forest cat', 'Norwegian Forest Cat'), ('oriental shorthair', 'Oriental Shorthair'), ('persian', 'Persian'), ('russian blue', 'Russian Blue'), ('scottish fold', 'Scottish Fold'), ('siamese', 'Siamese'), ('siberian', 'Siberian'), ('sphynx', 'Sphynx')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('doberman', 'Doberman'), ('border', 'Border'), ('pitbull', 'Pitbull'), ('husky', 'Husky'), ('labrador', 'Labrador'), ('rottweiler', 'Rottweiler'), ('beagle', 'Beagle'), ('bulldog', 'Bulldog'), ('german shepherd', 'German Shepherd'), ('poodle', 'Poodle'), ('boxer', 'Boxer'), ('pug', 'Pug'), ('pomeranian', 'Pomeranian'), ('chihuahua', 'Chihuahua')], max_length=20),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_fn.cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cat')},
            },
        ),
    ]
